# -*- coding: utf-8 -*-
"""mini_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oix8p1-f4oz_bk-GL6mPYCdqWPyJ_bcs
"""

#task-9
#Develop  a student record management system



