# -*- coding: utf-8 -*-
"""Mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16EGRsWGXmIx7zUhPiED8LrLIM9-dUnVw
"""

# Student Record Management System

students = []

def add_student():
    name = input("Enter student name: ")
    roll = int(input("Enter roll number: "))
    course = input("Enter course: ")

    student = {
        "Name": name,
        "Roll No": roll,
        "Course": course
    }

    students.append(student)
    print("Student added successfully!\n")


def display_students():
    if len(students) == 0:
        print("No student records found.\n")
    else:
        print("\nStudent Records:")
        for student in students:
            print("Name:", student["Name"])
            print("Roll No:", student["Roll No"])
            print("Course:", student["Course"])
            print("-------------------")


def search_student():
    name = input("Enter student name to search: ")
    found = False

    for student in students:
        if student["Name"].lower() == name.lower():
            print("Student Found:")
            print("Name:", student["Name"])
            print("Roll No:", student["Roll No"])
            print("Course:", student["Course"])
            found = True
            break

    if not found:
        print("Student not found.\n")


def delete_student():
    name = input("Enter student name to delete: ")

    for student in students:
        if student["Name"].lower() == name.lower():
            students.remove(student)
            print("Student record deleted successfully!\n")
            return

    print("Student not found.\n")


while True:
    print("\n--- Student Record Management System ---")
    print("1. Add Student")
    print("2. Display Students")
    print("3. Search Student")
    print("4. Delete Student")
    print("5. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        add_student()
    elif choice == 2:
        display_students()
    elif choice == 3:
        search_student()
    elif choice == 4:
        delete_student()
    elif choice == 5:
        print("Program exited.")
        break
    else:
        print("Invalid choice. Please try again.")