# -*- coding: utf-8 -*-
"""python assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEbUgKOdyHf8JcB8oAwZUILced4a6lEK
"""

#TASK-1
""" """

print("Welcome to the Student Information Program")
name = input("Enter your name: ")
college = input("Enter your college name: ")
branch = input("Enter your branch: ")
print("\n----- Student Details -----")
print("Name    :", name)
print("College :", college)
print("Branch  :", branch)
print("---------------------------")

#TASK -2

name = "Rahul"
age = 20
height = 5.8
is_student = True
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Student:", is_student)

# TASK-3

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)
print("Modulus =", a % b)

#task4

marks = int(input("Enter your marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 60:
    print("Grade C")
else:
    print("Fail")

#task 5
for i in range(1, 21):
  print(i)

# Multiplication table of any number
num = int(input("Enter a number: "))
for i in range(1, 11):
    print(num, "x", i, "=", num * i)

num = 2
while num <= 50:
  print(num)
  num = num + 2

#task 6
def square(num):
  return num * num
number = int(input("Enter a number: "))
print("Square =", square(number))

# Function to calculate the average of three numbers
def average(a, b, c):
  return (a + b + c) / 3
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))
print("Average =", average(num1, num2, num3))

#Task-7:Strings & Collections
# String operations
text = "Hello Python"
print("Original String:", text)
print("Upper Case:", text.upper())
print("Lower Case:", text.lower())
print("Replace:", text.replace("Python", "World"))
print("Find 'Python':", text.find("Python"))

# List operations
numbers = [40, 10, 30, 20]
numbers.append(50)
print("After append:", numbers)
numbers.remove(30)
print("After remove:", numbers)
numbers.sort()
print("After sort:", numbers)

fruits = ("Apple", "Banana", "Mango", "Orange")
print("Tuple:", fruits)
print("First Fruit:", fruits[0])
print("Third Fruit:", fruits[2])

# Dictionary example
student = {
"Name": "Rahul",
"Roll No": 101,
"Course": "BCA",
"Marks": 90
}
print("Student Information")
print("Name:", student["Name"])
print("Roll No:", student["Roll No"])
print("Course:", student["Course"])
print("Marks:", student["Marks"])

# Set operations
colors = {"Red", "Green", "Blue"}
colors.add("Yellow")
print("After add:", colors)
colors.remove("Green")
print("After remove:", colors)

#Task-8 file handling
# Create a file and write an introduction
with open("introduction.txt", "w") as file:
    file.write("My name is rani.\n")
    file.write("I am a graduate.\n")
    file.write("I am learning Python programming.\n")
    file.write("I enjoy coding and solving problems.")

# Read and display the file contents
with open("introduction.txt", "r") as file:
    content = file.read()
    print("File Contents:")
    print(content)

