# -*- coding: utf-8 -*-
"""Week-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uM9mLkk9SS7SHXFzJSCNmQD89ezhoYFA
"""

#Task-1: Numpy Introduction & Arrays
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

one_d = np.array([1, 2, 3, 4, 5])
two_d = np.array([[1, 2, 3], [4, 5, 6]])

print("One-dimensional array:", one_d)
print("Two-dimensional array:")
print(two_d)

#Task-2:Numpy Indexing ,Slicing & Reshaping
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print("Original array:", arr)
print("Element at index 2:", arr[2])
print("Elements from index 1 to 4:", arr[1:5])

matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print("Matrix:")
print(matrix)
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])

reshaped = arr.reshape(2, 3)
print("Reshaped array:")
print(reshaped)

#Task-3: Numpy Mathematical & Statiatical Operations
import numpy as np
a = np.array([10, 20, 30, 40, 50])
b = np.array([2, 4, 5, 8, 10])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Minimum:", np.min(a))
print("Maximum:", np.max(a))
print("Standard Deviation:", round(np.std(a), 2))
print("Sum:", np.sum(a))

#TAsk-4 Pandaa series & Dataframe
import pandas as pd
marks = pd.Series([85, 78, 92, 88, 76],
                  index=["Asha", "Ravi", "John", "Priya", "Kiran"])
df = pd.DataFrame({
    "Name": ["Asha", "Ravi", "John", "Priya", "Kiran"],
    "Age": [20, 21, 20, 22, 21],
    "Marks": [85, 78, 92, 88, 76]
})
print("Pandas Series:")
print(marks)
print("\nOriginal DataFrame:")
print(df)
print("\nColumn names:", list(df.columns))
print("Index:", list(df.index))
df["Result"] = ["Pass", "Pass", "Pass", "Pass", "Pass"]
print("\nUpdated DataFrame:")
print(df)

#Task-5: Reading & Inspecting Data:
import pandas as pd
df = pd.read_csv("sales_dataset.csv")
print("First 5 rows:")
print(df.head())
print("\nLast 5 rows:")
print(df.tail())
print("\nRows and columns:", df.shape)
print("\nColumn names:", list(df.columns))
print("\nData types:")
print(df.dtypes)
print("\nDataset information:")
print(df.info())
print("\nDescriptive statistics:")
print(df.describe())

#Task-6:Selecting ,filtering & Sorting Data
import pandas as pd
df = pd.read_csv("sales_dataset.csv")
print("Selected columns:")
print(df[["Product", "Region", "Sales"]])
print("\nSelected rows (first 3):")
print(df.iloc[:3])
print("\nSales greater than 60000:")
print(df[df["Sales"] > 60000][["Product", "Region", "Sales"]])

print("\nMultiple conditions (South and Sales > 50000):")
print(df[(df["Region"] == "South") & (df["Sales"] > 50000)]
      [["Product", "Sales"]])

print("\nAscending order by Sales:")
print(df.sort_values("Sales")[["Product", "Sales"]])

print("\nDescending order by Sales:")
print(df.sort_values("Sales", ascending=False)[["Product", "Sales"]])

#Task-7: Handling Missing Values
import pandas as pd
df = pd.read_csv("sales_missing_dataset.csv")
print("Missing values before handling:")
print(df.isnull().sum())
print("\nRows after removing missing values:")
print(df.dropna())
cleaned = df.copy()
cleaned["Price"] = cleaned["Price"].fillna(cleaned["Price"].mean())
cleaned["Quantity"] = cleaned["Quantity"].fillna(cleaned["Quantity"].median())
cleaned["Region"] = cleaned["Region"].fillna("Unknown")
print("\nDataset after filling missing values:")
print(cleaned)

#task8:Merge,Concatenate,Groupby &Pivot Table
import pandas as pd

df1 = pd.read_csv("sales_part1.csv")
df2 = pd.read_csv("sales_part2.csv")

# Merge using the common Category column
category_sales = pd.DataFrame({
    "Category": ["Electronics", "Accessories"],
    "Target": [250000, 30000]
})

category_actual = (
    pd.concat([df1, df2])
      .groupby("Category", as_index=False)["Sales"]
      .sum()
      .rename(columns={"Sales": "Actual_Sales"})
)

merged = pd.merge(category_actual, category_sales, on="Category")
print("Merged DataFrame:")
print(merged)

concatenated = pd.concat([df1, df2], ignore_index=True)
print("\nConcatenated DataFrame:")
print(concatenated)

print("\nGroupBy - total sales by Region:")
print(concatenated.groupby("Region")["Sales"].sum())

print("\nGroupBy - average sales by Category:")
print(concatenated.groupby("Category")["Sales"].mean())

pivot = pd.pivot_table(
    concatenated,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)
print("\nPivot Table:")
print(pivot)

#task-9: Exporting Data

import pandas as pd
df = pd.read_csv("sales_dataset.csv")
df["Sales_per_Unit"] = df["Sales"] / df["Quantity"]
output_file = "processed_sales.csv"
df.to_csv(output_file, index=False)
check = pd.read_csv(output_file)
print("File exported successfully:", output_file)
print("Rows and columns:", check.shape)
print("\nExported data:")
print(check.head())

#task-10:Mini Project
import pandas as pd
import numpy as np

df = pd.read_csv("sales_dataset.csv")

print("1. Dataset shape:", df.shape)

print("\n2. Total Sales:", df["Sales"].sum())
print("3. Average Sales:", df["Sales"].mean())

print("\n4. Sales by Region:")
print(df.groupby("Region")["Sales"].sum())

print("\n5. Sales by Category:")
print(df.groupby("Category")["Sales"].sum())

print("\n6. Top 3 products by sales:")
print(df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(3))

pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Category",
    aggfunc="sum",
    fill_value=0
)

print("\n7. Pivot Table:")
print(pivot)

df["Sales_per_Unit"] = df["Sales"] / df["Quantity"]
df.to_csv("cleaned_sales_analysis.csv", index=False)

print("\n8. Cleaned dataset exported successfully.")