# -*- coding: utf-8 -*-
"""Week-4_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gLfonmQ9PItgdw3A_niH4EE7o5kJ8I2
"""

# Week 4 Assignment: Statistics, Data Visualization & EDA
**Dataset:** `chocolate_cleaned.csv` (Chocolate Sales Data)

Columns: `Sales Person`, `Country`, `Product`, `Date`, `Amount`, `Boxes Shipped`

This notebook covers:
- Task 1 — Mean, Median, Mode
- Task 2 — Variance & Standard Deviation
- Task 3 — Correlation & Probability Basics
- Task 4 — Outlier Detection
- Task 5 — Matplotlib Visualization
- Task 6 — Seaborn Visualization
- Task 7 — EDA: Data Inspection & Cleaning
- Task 8 — EDA: Correlation & Insights
- Task 9 — Business Recommendations

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

df = pd.read_csv("chocolate_cleaned.csv")
df["Date"] = pd.to_datetime(df["Date"])

#TASK-7 :Exploratory Data Analysis (EDA)- data inspection & cleaning

#check no.of columns and rows
df.shape

# display names of the columns
df.columns

# check the datatype
df.dtypes

#genarate a statistical summary
df.describe()

#Data cleaning

#checking duplicates
n_dup=df.duplicated().sum()
print("no. of  duplicate rows:",n_dup)

#handling missing values
df.isnull().sum()

# Check for inconsistent values
print("Negative Amount values:", (df["Amount"] < 0).sum())
print("Negative Boxes Shipped values:", (df["Boxes Shipped"] < 0).sum())
print("Unique Country values:", df["Country"].unique())
print("Unique Product count:", df["Product"].nunique())

df.head()

**Explanation:** The dataset was already fairly clean (no missing values or duplicates found), but the
cleaning steps above (imputing missing values, dropping duplicates, checking for negative/inconsistent
values) were still applied as a safeguard, following standard EDA practice before analysis.

#task-1 statistical Analysis -mean, median & mode
mean=df["Amount"].mean()
median=df["Amount"].median()
mode=df["Amount"].mode()
print("mean amount is:",mean)
print("median amount is:",median)
print("mode amount is:",mode)

**Explanation:**
- **Mean:** the average sales amount per transaction; sensitive to extreme/high values.
- **Median:** the middle value when sorted; a more robust typical transaction size since it isn't pulled by very large sales.
- **Mode:** the most frequently occurring sales amount, showing a common transaction value.

#Task-2: Variance & Standard deviation
amount_var = df["Amount"].var()
amount_std = df["Amount"].std()
print("variance:",amount_var)b
print("standard deviation :",amount_std)

**Explanation:** Variance shows how spread out sales amounts are from the mean, in squared units.
Standard deviation (same units as the data) shows the typical distance of a transaction's value from
the mean. A high standard deviation here means sales amounts vary widely across transactions rather
than clustering tightly around the mean.

#task-3: Correlation & Probability Basics
correlation = df["Amount"].corr(df["Boxes Shipped"])
print(f"Correlation between Amount and Boxes Shipped: {correlation:.4f}")

if correlation > 0.5:
    strength = "a strong positive"
elif correlation > 0.1:
    strength = "a weak-to-moderate positive"
elif correlation > -0.1:
    strength = "almost no (weak/negligible)"
elif correlation > -0.5:
    strength = "a weak-to-moderate negative"
else:
    strength = "a strong negative"

print(f"This indicates {strength} relationship between Amount and Boxes Shipped.")

# Probability example: probability that a random sale is from India
prob_india = (df["Country"] == "India").mean()
print(f"P(a random sale is from India) = {prob_india:.4f} ({prob_india*100:.2f}%)")
print("Calculated as (number of India sales) / (total number of sales).")

#task-4 :outlier Detection
Q1 = df["Amount"].quantile(0.25)
Q3 = df["Amount"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["Amount"] < lower_bound) | (df["Amount"] > upper_bound)]

print(f"Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
print(f"Lower bound: {lower_bound:.2f}, Upper bound: {upper_bound:.2f}")
print(f"Number of outliers detected: {len(outliers)}")

outliers[["Sales Person", "Country", "Product", "Amount"]].head(10)

**Explanation:** Outliers are transactions with unusually high (or low) sales amounts compared to
the rest of the data. They can skew the mean and inflate variance/standard deviation, distort
correlation results, and mislead trend analysis if not handled properly. It's important to investigate
whether outliers are genuine large sales or data entry errors before deciding to keep, cap, or remove them.

#task-5: Matplotlib Visualization
# Line Chart: Monthly total sales trend
monthly_sales = df.set_index("Date").resample("ME")["Amount"].sum()

plt.figure(figsize=(10, 5))
plt.plot(monthly_sales.index, monthly_sales.values, marker="o", color="saddlebrown")
plt.title("Line Chart: Monthly Total Sales Amount")
plt.xlabel("Month")
plt.ylabel("Total Sales Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

*Explanation: shows how total sales amount fluctuates month to month.*

# Bar Chart: Total sales by country
country_sales = df.groupby("Country")["Amount"].sum().sort_values(ascending=False)

plt.figure(figsize=(8, 5))
plt.bar(country_sales.index, country_sales.values, color="chocolate")
plt.title("Bar Chart: Total Sales by Country")
plt.xlabel("Country")
plt.ylabel("Total Sales Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

*Explanation: compares total sales across countries, highlighting top markets.*

# Pie Chart: Sales share by country
plt.figure(figsize=(7, 7))
plt.pie(country_sales.values, labels=country_sales.index, autopct="%1.1f%%",
        colors=sns.color_palette("Wistia", len(country_sales)))
plt.title("Pie Chart: Sales Share by Country")
plt.tight_layout()
plt.show()

*Explanation: shows each country s percentage share of total sales.*

# Histogram: Distribution of sales amount
plt.figure(figsize=(8, 5))
plt.hist(df["Amount"], bins=30, color="peru", edgecolor="black")
plt.title("Histogram: Distribution of Sales Amount")
plt.xlabel("Amount")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

*Explanation: most transactions cluster at lower amounts with a right-skewed tail.*

#Scatter plot : Boxes shipped vs amount
plt.figure(figsize=(8, 5))
plt.scatter(df["Boxes Shipped"], df["Amount"], alpha=0.4, color="darkorange")
plt.title("Scatter Plot: Boxes Shipped vs Amount")
plt.xlabel("Boxes Shipped")
plt.ylabel("Amount")
plt.tight_layout()
plt.show()

*Explanation: points are widely scattered with no clear linear pattern, consistent with the
near-zero correlation found in Task 3.*

#task-6:Seaborn Visualization

# Count Plot: number of transactions per country
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x="Country", order=df["Country"].value_counts().index,
              hue="Country", palette="Oranges_r", legend=False)
plt.title("Count Plot: Number of Transactions per Country")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

*Explanation: points are widely scattered with no clear linear pattern, consistent with the
near-zero correlation found in Task 3.*

# Box Plot: Amount distribution by country
plt.figure(figsize=(9, 5))
sns.boxplot(data=df, x="Country", y="Amount", hue="Country", palette="YlOrBr", legend=False)
plt.title("Box Plot: Sales Amount by Country")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

*Explanation: shows the spread and outliers of sales amount within each country.*

# Heatmap: correlation between numeric variables
numeric_cols = df[["Amount", "Boxes Shipped"]]

plt.figure(figsize=(5, 4))
sns.heatmap(numeric_cols.corr(), annot=True, cmap="coolwarm")
plt.title("Heatmap: Correlation Matrix")
plt.tight_layout()
plt.show()

*Explanation: visualizes the strength of correlation between Amount and Boxes Shipped.*

# Pair Plot
pairplot_fig = sns.pairplot(df[["Amount", "Boxes Shipped"]])
pairplot_fig.fig.suptitle("Pair Plot: Amount vs Boxes Shipped", y=1.02)
plt.show()

*Explanation: shows pairwise relationships and individual distributions of the two numeric
variables together.*

#task-8: EDA- Correlation & insights
top_product = df.groupby("Product")["Amount"].sum().idxmax()
top_country = country_sales.idxmax()
top_person = df.groupby("Sales Person")["Amount"].sum().idxmax()

print("Top-selling product by revenue:", top_product)
print("Top-selling country by revenue:", top_country)
print("Top sales person by revenue:", top_person)
print(f"Correlation (Amount vs Boxes Shipped): {correlation:.4f}")

**Key Insights:**
1. Amount and Boxes Shipped show almost no (weak/negligible) relationship, meaning the number of
   boxes shipped in a transaction is not a reliable predictor of that transaction's revenue in this
   dataset — pricing likely varies a lot by product rather than scaling simply with volume.
2. Sales revenue is not evenly distributed across countries — the top country contributes noticeably
   more than the others.
3. A small number of products and sales people account for a large portion of total sales, following
   a typical Pareto-style ("80/20") distribution.

# task-9 :BUSINESS RECOMMENDATIONS
1. **Focus on top performers:** Prioritize marketing and inventory investment on the top-selling
   product and top-performing country, since they drive the largest share of revenue — supported by
   the aggregation in Task 8.
2. **Dont rely on volume alone:** Since Amount and Boxes Shipped show almost no correlation, pushing
   larger box quantities per order is unlikely to reliably raise revenue on its own. Instead, focus on
   selling higher-priced/higher-margin products per shipment.
3. **Review outlier transactions:** Investigate the outlier transactions identified in Task 4 — if
   genuine large orders, consider a dedicated large-order sales process; if data errors, correct them
   to avoid skewing future reporting.